In [14]:
import pandas as pd
import numpy as np

In [15]:
data = pd.read_csv("k_means_output.csv")

In [16]:
data.head(46)

                location  frequency  latitude  longitude  Cluster
0            azad maidan   0.000000  0.071301   0.234205        2
1                 bandra   0.432432  0.415871   0.265475        1
2               bhoiwada   0.027027  0.315334   0.367581        2
3                    bkc   0.243243  0.453759   0.403957        1
4               borivali   0.270270  0.937053   0.374601        4
5                byculla   0.000000  0.184666   0.216337        2
6                chembur   0.729730  0.439439   0.654116        0
7            chunabhatti   0.000000  0.397375   0.548181        3
8                 colaba   0.054054  0.000000   0.173580        2
9               d.b.marg   0.027027  0.083234   0.230377        2
10                 dadar   0.675676  0.311158   0.279515        0
11               dahisar   0.243243  1.000000   0.388641        4
12                deonar   0.000000  0.406921   0.677090        3
13               dharavi   0.081081  0.369928   0.362476        2
14              dindoshi   0.216216  0.767601   0.406509        4
15             ghatkopar   0.108108  0.511635   0.698149        3
16              goregaon   0.513514  0.744630   0.323548        1
17            jogeshwari   0.297297  0.656026   0.320357        1
18             kalbadevi   0.054054  0.103520   0.209317        2
19             kandivali   0.189189  0.875298   0.278239        4
20            kanjurmarg   0.000000  0.645585   0.825782        3
21                 kurla   0.297297  0.483890   0.514997        1
22                 mahim   0.054054  0.360680   0.266114        2
23                 malad   0.540541  0.810561   0.319081        1
24            malbarhill   0.000000  0.128878   0.000000        2
25              mankhurd   0.162162  0.398568   0.892151        3
26           marinedrive   0.000000  0.088604   0.160817        2
27               matunga   0.351351  0.334129   0.362476        1
28                   MHB   0.000000  0.794153   0.283344        4
29                  MIDC   0.324324  0.606504   0.422463        1
30                mulund   0.351351  0.766110   1.000000        3
31            D.N. nagar   1.000000  0.640513   0.195916        0
32               nagpada   0.054054  0.159010   0.178047        2
33              oshiwara   0.189189  0.713007   0.289087        4
34                 powai   0.243243  0.607697   0.693682        3
35              pydhunie   0.108108  0.117243   0.221442        2
36  sahar police station   0.405405  0.552804   0.405871        1
37              sakinaka   0.216216  0.553699   0.589662        3
38            samtanagar   0.270270  0.878580   0.372687        4
39             Santacruz   0.432432  0.497613   0.274410        1
40                tardeo   0.297297  0.166468   0.095086        2
41               Trombey   0.000000  0.463902   0.098915        2
42                vakola   0.243243  0.491647   0.355456        1
43              vikhroli   0.189189  0.607697   0.828334        3
44                wadala   0.081081  0.328162   0.417358        2
45                 worli   0.216216  0.288484   0.126356        2

In [17]:
features = data[["frequency", "latitude", "longitude"]].values

In [18]:
features

array([[0.        , 0.07130072, 0.23420549],
       [0.43243243, 0.41587112, 0.26547543],
       [0.02702703, 0.31533413, 0.36758137],
       [0.24324324, 0.45375895, 0.4039566 ],
       [0.27027027, 0.93705251, 0.37460115],
       [0.        , 0.18466587, 0.21633695],
       [0.72972973, 0.43943914, 0.65411615],
       [0.        , 0.3973747 , 0.54818124],
       [0.05405405, 0.        , 0.17358009],
       [0.02702703, 0.08323389, 0.23037652],
       [0.67567568, 0.31115752, 0.279515  ],
       [0.24324324, 1.        , 0.38864071],
       [0.        , 0.40692124, 0.67708998],
       [0.08108108, 0.3699284 , 0.36247607],
       [0.21621622, 0.76760143, 0.40650925],
       [0.10810811, 0.51163484, 0.69814933],
       [0.51351351, 0.74463007, 0.32354818],
       [0.2972973 , 0.65602625, 0.32035737],
       [0.05405405, 0.10352029, 0.20931717],
       [0.18918919, 0.87529833, 0.27823867],
       [0.        , 0.64558473, 0.82578175],
       [0.2972973 , 0.48389021, 0.51499681],
       [0.05405405, 0.36068019, 0.26611359],
       [0.54054054, 0.81056086, 0.31908105],
       [0.        , 0.12887828, 0.        ],
       [0.16216216, 0.39856802, 0.89215061],
       [0.        , 0.08860382, 0.16081685],
       [0.35135135, 0.33412888, 0.36247607],
       [0.        , 0.79415274, 0.28334397],
       [0.32432432, 0.60650358, 0.42246331],
       [0.35135135, 0.76610979, 1.        ],
       [1.        , 0.64051313, 0.19591576],
       [0.05405405, 0.15900955, 0.17804722],
       [0.18918919, 0.71300716, 0.28908743],
       [0.24324324, 0.6076969 , 0.6936822 ],
       [0.10810811, 0.11724344, 0.22144225],
       [0.40540541, 0.5528043 , 0.40587109],
       [0.21621622, 0.55369928, 0.58966177],
       [0.27027027, 0.87857995, 0.37268666],
       [0.43243243, 0.49761337, 0.2744097 ],
       [0.2972973 , 0.16646778, 0.09508615],
       [0.        , 0.46390215, 0.09891512],
       [0.24324324, 0.49164678, 0.35545629],
       [0.18918919, 0.6076969 , 0.8283344 ],
       [0.08108108, 0.32816229, 0.41735801],
       [0.21621622, 0.28848449, 0.12635609]])

In [19]:
# Extract the cluster indices into a numpy array
cluster_indices = data["Cluster"].values
cluster_indices

array([2, 1, 2, 1, 4, 2, 0, 3, 2, 2, 0, 4, 3, 2, 4, 3, 1, 1, 2, 4, 3, 1,
       2, 1, 2, 3, 2, 1, 4, 1, 3, 0, 2, 4, 3, 2, 1, 3, 4, 1, 2, 2, 1, 3,
       2, 2], dtype=int64)

In [20]:

# Loop over each cluster and extract the corresponding data points

old_cluster = [[], [], [], [], []]
for i in range(cluster_indices.size):
    # Use boolean indexing to extract the data points for this cluster
    old_cluster[cluster_indices[i]].append(i);
clusters = []
for i in range(len(old_cluster)) :
    clusters.append(np.array(old_cluster[i]))
clusters

[array([ 6, 10, 31]),
 array([ 1,  3, 16, 17, 21, 23, 27, 29, 36, 39, 42]),
 array([ 0,  2,  5,  8,  9, 13, 18, 22, 24, 26, 32, 35, 40, 41, 44, 45]),
 array([ 7, 12, 15, 20, 25, 30, 34, 37, 43]),
 array([ 4, 11, 14, 19, 28, 33, 38])]

Clusters indexes of initial population

In [21]:
clusters

[array([ 6, 10, 31]),
 array([ 1,  3, 16, 17, 21, 23, 27, 29, 36, 39, 42]),
 array([ 0,  2,  5,  8,  9, 13, 18, 22, 24, 26, 32, 35, 40, 41, 44, 45]),
 array([ 7, 12, 15, 20, 25, 30, 34, 37, 43]),
 array([ 4, 11, 14, 19, 28, 33, 38])]

In [ ]:
population = features 
population

In [22]:
bitPopulation = []
bitCluster = "0"*46

for clusterItem in clusters:
    for loc in clusterItem:
        bitCluster = bitCluster[:loc] + "1" + bitCluster[loc + 1:]
    bitPopulation.append(bitCluster)
    bitCluster = "0"*46
    
bitPopulation

['0000001000100000000000000000000100000000000000',
 '0101000000000000110001010001010000001001001000',
 '1010010011000100001000101010000010010000110011',
 '0000000100001001000010000100001000100100000100',
 '0000100000010010000100000000100001000010000000']

Algorithm : 

1. problem definition :-  
a. To find the good clusters among the kmeans cluster i.e which has most frequency in hotspot   
b. A good cluster is represented by which has highest sum of frequency seperation score     

2. population in numpy arrays --> frequency , latitude and longitude , cluster no   
    population - output of kmeans algo

we represented 45 locations as binary string - "1000101000000000000001010"

3.  define fitness function(population , cluster)
     sum of frequencies represent fitness scores
     seperation of longitudes and latitudes

4.  selection 
    - select top 2 fit parents
     
5.  crossover 
     - cross over at random index 
6.  mutation : -
      - less fitness bits flipped 

7.  stop  result plot on the bubble map

![architechture](architechture.png)